pipeline:
  name: CDS-77208
  identifier: CDS77208
  projectIdentifier: Sandesh_Test
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: St1
        identifier: St1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: HarnessApproval
                  name: HarnessApproval_1
                  identifier: HarnessApproval_1
                  spec:
                    approvalMessage: Please review the following information and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    isAutoRejectEnabled: false
                    approvers:
                      userGroups:
                        - account._account_all_users
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1d
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo <+pipeline.stages.approve.spec.execution.steps.approve.status> == "SUCCEEDED"`
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
