pipeline:
  projectIdentifier: CDS71826
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Maintain Indexes DB1
        identifier: Maintain_Indexes_DB1
        template:
          templateRef: DB_Maintenance_IndexesApply
          versionLabel: v1
          templateInputs:
            type: Deployment
            spec:
              service:
                serviceRef: afDeployment
                serviceInputs:
                  serviceDefinition:
                    type: WinRm
                    spec:
                      artifacts:
                        primary:
                          primaryArtifactRef: aafreleases
                          sources:
                            - identifier: aafreleases
                              type: ArtifactoryRegistry
                              spec:
                                artifactPath: <+input>
              environment:
                useFromStage:
                  stage: Run_smart_maintenance_statistics
  identifier: DB_Maintenance_Only_Indexes
  description: Run statistics then indexes on all DBs in given environment
  name: DB Maintenance - Only Indexes
