pipeline:
  projectIdentifier: CDS71826
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Maintain statistics DB1
        identifier: Run_smart_maintenance_statistics
        template:
          templateRef: DB_Maintenance_StatisticsApply
          versionLabel: v1
          templateInputs:
            type: Deployment
            spec:
              service:
                serviceRef: afDeployment
                serviceInputs:
                  serviceDefinition:
                    type: WinRm
                    spec:
                      artifacts:
                        primary:
                          primaryArtifactRef: <+input>
                          sources: <+input>
              environment:
                environmentRef: <+input>
                environmentInputs: <+input>
                serviceOverrideInputs: <+input>
                infrastructureDefinitions: <+input>
              execution:
                steps:
                  - step:
                      identifier: Maintain_DB_Statistics
                      template:
                        templateInputs:
                          type: Command
                          spec:
                            type: Command
                            environmentVariables:
                              - name: dbConnectionString
                                type: String
                                value: <+serviceVariables.dbConnectionString>
  identifier: DM_maintenance_statistics_All_Clone
  description: Run statistics then indexes on all DBs in given environment
  name: DB Maintenance - Clone
