pipeline:
  name: test_remote_pipeline_fix_1
  identifier: test_remote_pipeline_fix_1
  projectIdentifier: DoNotDelete_Sandesh
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: cs_1
        identifier: cs_1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo 1
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
