pipeline:
  identifier: test_remote_pipeline_1
  name: test_remote_pipeline_1
  projectIdentifier: CDS71826
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        identifier: stage_1
        type: Custom
        name: stage_1
        description: ""
        spec:
          execution:
            steps:
              - step:
                  identifier: ShellScript_1
                  type: ShellScript
                  name: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo 0
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: deploy_1
        identifier: deploy_1
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: service_1
          environment:
            environmentRef: test_1
            deployToAll: false
            infrastructureDefinitions:
              - identifier: infrs_1
                inputs:
                  identifier: infrs_1
                  type: KubernetesDirect
                  spec:
                    connectorRef: <+input>
                    environmentVariables:
                      - name: var_1
                        type: String
                        value: <+input>
          execution:
            steps:
              - step:
                  identifier: ShellScript_2
                  type: ShellScript
                  name: ShellScript_2
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo 0
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
